"""initial

Revision ID: c497322e746b
Revises: 
Create Date: 2025-12-28 12:00:48.646421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c497322e746b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'STARTER', 'PROFESSIONAL', 'TEAM', 'ENTERPRISE', name='plantier'), nullable=False),
    sa.Column('plan_started_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_id', sa.String(length=255), nullable=True),
    sa.Column('execution_limit', sa.Integer(), nullable=False),
    sa.Column('executions_used', sa.Integer(), nullable=False),
    sa.Column('workflow_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_plan', ['plan'], unique=False)

    op.create_table('credentials',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('OPENAI_TOKEN', 'ANTHROPIC_TOKEN', 'GEMINI_TOKEN', name='credentialstype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=1255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credentials_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('workflows',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('avg_execution_time', sa.Float(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_workflows_nodes_gin', ['nodes'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_workflows_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_workflows_user_id_created_at', ['user_id', 'created_at'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_chat_sessions_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_chat_sessions_workflow', ['workflow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('executions',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=True),
    sa.Column('initial_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='executionstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('error_type', sa.Enum('CONFIGURATION_ERROR', 'VALIDATION_ERROR', 'RUNTIME_ERROR', 'TIMEOUT_ERROR', 'CYCLE_DETECTION', 'LOGIC_ERROR', 'SYSTEM_ERROR', name='executionerrortype'), nullable=True),
    sa.Column('failed_node_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('steps_count', sa.Integer(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index('ix_executions_chat_session', ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_chat_session_id'), ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_executions_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('ix_executions_workflow_created', ['workflow_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_chat_session_id'), ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_chat_messages_session_created', ['chat_session_id', 'created_at'], unique=False)

    op.create_table('execution_steps',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.Enum('START', 'AGENT', 'CONDITION', 'SET_VARIABLE', 'END', 'STICKER', name='nodetype'), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='stepstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('cel_evaluations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'step_number', name='uq_execution_step')
    )
    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_steps_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_steps_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index('ix_execution_steps_execution_step', ['execution_id', 'step_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_steps_node_type'), ['node_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_steps_node_type'))
        batch_op.drop_index('ix_execution_steps_execution_step')
        batch_op.drop_index(batch_op.f('ix_execution_steps_execution_id'))
        batch_op.drop_index(batch_op.f('ix_execution_steps_created_at'))

    op.drop_table('execution_steps')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_session_created')
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_chat_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executions_workflow_id'))
        batch_op.drop_index('ix_executions_workflow_created')
        batch_op.drop_index('ix_executions_user_status')
        batch_op.drop_index(batch_op.f('ix_executions_user_id'))
        batch_op.drop_index(batch_op.f('ix_executions_status'))
        batch_op.drop_index(batch_op.f('ix_executions_created_at'))
        batch_op.drop_index(batch_op.f('ix_executions_chat_session_id'))
        batch_op.drop_index('ix_executions_chat_session')

    op.drop_table('executions')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_workflow_id'))
        batch_op.drop_index('ix_chat_sessions_workflow')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index('ix_chat_sessions_user_active')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_is_active'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_created_at'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index('ix_workflows_user_id_created_at')
        batch_op.drop_index(batch_op.f('ix_workflows_user_id'))
        batch_op.drop_index('ix_workflows_nodes_gin', postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_workflows_is_active'))
        batch_op.drop_index(batch_op.f('ix_workflows_created_at'))

    op.drop_table('workflows')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_credentials_type'))
        batch_op.drop_index(batch_op.f('ix_credentials_created_at'))

    op.drop_table('credentials')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_plan')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('ix_users_created_at')

    op.drop_table('users')
    # ### end Alembic commands ###

