"""add payments

Revision ID: d62f737587b9
Revises: dccadc78a37b
Create Date: 2026-01-22 08:38:00.163813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd62f737587b9'
down_revision = 'dccadc78a37b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('organization_id', sa.Uuid(), nullable=False, comment='ID организации'),
    sa.Column('user_email', sa.String(length=255), nullable=False, comment='Email плательщика'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Сумма в копейках'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание платежа'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус платежа'),
    sa.Column('external_payment_id', sa.String(length=255), nullable=True, comment='ID платежа в платежной системе'),
    sa.Column('order_id', sa.String(length=255), nullable=False, comment='Уникальный ID заказа (UUID)'),
    sa.Column('target_plan', sa.String(length=50), nullable=False, comment='Целевой тарифный план'),
    sa.Column('is_recurrent', sa.Boolean(), nullable=False, comment='Рекуррентный платеж (с привязкой карты)'),
    sa.Column('rebill_id', sa.Integer(), nullable=True, comment='ID для автоматического списания (RebillId от Tinkoff)'),
    sa.Column('parent_payment_id', sa.Uuid(), nullable=True, comment='ID родительского платежа (для рекуррентных списаний)'),
    sa.Column('payment_url', sa.Text(), nullable=True, comment='URL для оплаты'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Провайдер платежной системы (tinkoff, yookassa, stripe)'),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Дополнительные метаданные платежа'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_external_payment_id'), ['external_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=True)
        batch_op.create_index('ix_payments_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index('ix_payments_organization_id', ['organization_id'], unique=False)
        batch_op.create_index('ix_payments_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_status')
        batch_op.drop_index('ix_payments_organization_id')
        batch_op.drop_index('ix_payments_org_status')
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_external_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))

    op.drop_table('payments')
    # ### end Alembic commands ###

