"""add google provider

Revision ID: dccadc78a37b
Revises: 46a3a3b0d222
Create Date: 2026-01-17 08:45:44.418851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccadc78a37b'
down_revision = '46a3a3b0d222'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('total_credits',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=None,
               existing_comment='Суммарное количество использованных кредитов',
               existing_nullable=False)

    with op.batch_alter_table('client_sessions', schema=None) as batch_op:
        batch_op.alter_column('total_credits',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=None,
               existing_comment='Суммарное количество использованных кредитов',
               existing_nullable=False)

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.alter_column('total_credits',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=None,
               existing_comment='Суммарное количество использованных кредитов (только системные ключи с маржой)',
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('provider_user_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('provider_user_id')
        batch_op.drop_column('auth_provider')

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.alter_column('total_credits',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=sa.text("'0'::numeric"),
               existing_comment='Суммарное количество использованных кредитов (только системные ключи с маржой)',
               existing_nullable=False)

    with op.batch_alter_table('client_sessions', schema=None) as batch_op:
        batch_op.alter_column('total_credits',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=sa.text("'0'::numeric"),
               existing_comment='Суммарное количество использованных кредитов',
               existing_nullable=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('total_credits',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=sa.text("'0'::numeric"),
               existing_comment='Суммарное количество использованных кредитов',
               existing_nullable=False)

    # ### end Alembic commands ###

