"""add is_test

Revision ID: a7776fcd12e8
Revises: ce99c0da1bed
Create Date: 2026-02-05 12:12:54.001778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7776fcd12e8'
down_revision = 'ce99c0da1bed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), server_default='false', nullable=False, comment='Флаг тестового пользователя'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_test')

    # ### end Alembic commands ###

