"""Добавил стоимость в кредитах

Revision ID: 46a3a3b0d222
Revises: 5c31ad68cf4d
Create Date: 2026-01-15 20:41:47.945356

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "46a3a3b0d222"
down_revision = "5c31ad68cf4d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "total_credits",
                sa.Numeric(precision=20, scale=8),
                nullable=False,
                server_default="0",
                comment="Суммарное количество использованных кредитов",
            )
        )
        batch_op.drop_column("total_cost")
        batch_op.drop_column("total_tokens_used")

    with op.batch_alter_table("client_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "total_credits",
                sa.Numeric(precision=20, scale=8),
                nullable=False,
                server_default="0",
                comment="Суммарное количество использованных кредитов",
            )
        )
        batch_op.drop_column("total_cost")
        batch_op.drop_column("total_tokens_used")

    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "total_credits",
                sa.Numeric(precision=20, scale=8),
                nullable=False,
                server_default="0",
                comment="Суммарное количество использованных кредитов (только системные ключи с маржой)",
            )
        )
        batch_op.drop_column("total_cost")
        batch_op.drop_column("total_tokens_used")

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.create_index(
            batch_op.f("ix_organizations_slug"), ["slug"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.create_index(
            batch_op.f("ix_organizations_slug"), ["slug"], unique=False
        )

    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "total_tokens_used", sa.INTEGER(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "total_cost",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("total_credits")

    with op.batch_alter_table("client_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "total_tokens_used",
                sa.INTEGER(),
                autoincrement=False,
                nullable=False,
                comment="Суммарное количество использованных токенов",
            )
        )
        batch_op.add_column(
            sa.Column(
                "total_cost",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
                comment="Суммарная стоимость (USD)",
            )
        )
        batch_op.drop_column("total_credits")

    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "total_tokens_used", sa.INTEGER(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "total_cost",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("total_credits")

    # ### end Alembic commands ###
