"""add billing

Revision ID: ac62578cd41b
Revises: 6f29c14b4ea3
Create Date: 2026-01-13 07:44:27.311937

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ac62578cd41b"
down_revision = "6f29c14b4ea3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_usage",
        sa.Column(
            "organization_id", sa.Uuid(), nullable=False, comment="ID организации"
        ),
        sa.Column(
            "period_start",
            sa.Date(),
            nullable=False,
            comment="Дата начала биллингового периода",
        ),
        sa.Column(
            "requests_used",
            sa.Integer(),
            nullable=False,
            comment="Количество использованных requests (non-debug executions) за период",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "period_start", name="uq_organization_usage_org_period"
        ),
    )
    with op.batch_alter_table("organization_usage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organization_usage_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_organization_usage_org_period",
            ["organization_id", "period_start"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_organization_usage_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_organization_usage_period_start"),
            ["period_start"],
            unique=False,
        )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "plan",
                sa.Enum("FREE", "PRO", "BUSINESS", name="plantier"),
                nullable=False,
                server_default="FREE",
                comment="Тарифный план организации",
            )
        )
        batch_op.add_column(
            sa.Column(
                "billing_period_start",
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("CURRENT_TIMESTAMP"),
                comment="Дата начала биллингового периода",
            )
        )
        batch_op.add_column(
            sa.Column(
                "subscription_id",
                sa.String(length=255),
                nullable=True,
                comment="ID подписки в платежной системе (Stripe/YooKassa)",
            )
        )
        batch_op.create_index(
            batch_op.f("ix_organizations_plan"), ["plan"], unique=False
        )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.alter_column(
            "state_schema",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            server_default=None,
            existing_comment="Схема проектных переменных для ClientSession",
            existing_nullable=False,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_plan"))
        batch_op.drop_column("subscription_id")
        batch_op.drop_column("workflow_limit")
        batch_op.drop_column("plan_started_at")
        batch_op.drop_column("executions_used")
        batch_op.drop_column("execution_limit")
        batch_op.drop_column("plan")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "plan",
                postgresql.ENUM(
                    "FREE",
                    "STARTER",
                    "PROFESSIONAL",
                    "TEAM",
                    "ENTERPRISE",
                    name="plantier",
                ),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "execution_limit", sa.INTEGER(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "executions_used", sa.INTEGER(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "plan_started_at",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "workflow_limit", sa.INTEGER(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "subscription_id",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.create_index(batch_op.f("ix_users_plan"), ["plan"], unique=False)

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.alter_column(
            "state_schema",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            existing_comment="Схема проектных переменных для ClientSession",
            existing_nullable=False,
        )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_plan"))
        batch_op.drop_column("subscription_id")
        batch_op.drop_column("billing_period_start")
        batch_op.drop_column("plan")

    with op.batch_alter_table("organization_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organization_usage_period_start"))
        batch_op.drop_index(batch_op.f("ix_organization_usage_organization_id"))
        batch_op.drop_index("ix_organization_usage_org_period")
        batch_op.drop_index(batch_op.f("ix_organization_usage_created_at"))

    op.drop_table("organization_usage")
    # ### end Alembic commands ###
