"""add notifications

Revision ID: 2b83435823c3
Revises: 6243d9f0ba55
Create Date: 2026-06-01 05:23:11.538596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b83435823c3'
down_revision = '6243d9f0ba55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('TELEGRAM', name='notificationchanneltype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_channels_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_channels_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_channels_type'), ['type'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_channels_type'))
        batch_op.drop_index(batch_op.f('ix_notification_channels_project_id'))
        batch_op.drop_index(batch_op.f('ix_notification_channels_created_at'))

    op.drop_table('notification_channels')
    # ### end Alembic commands ###

