"""delete org_usage

Revision ID: 6dc619ebd9ef
Revises: 01c0a8478c02
Create Date: 2026-01-15 15:32:07.383298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dc619ebd9ef'
down_revision = '01c0a8478c02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_usage_created_at'))
        batch_op.drop_index(batch_op.f('ix_organization_usage_org_period'))
        batch_op.drop_index(batch_op.f('ix_organization_usage_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_usage_period_start'))

    op.drop_table('organization_usage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_usage',
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID организации'),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False, comment='Дата начала биллингового периода'),
    sa.Column('requests_used', sa.INTEGER(), autoincrement=False, nullable=False, comment='Количество использованных requests (non-debug executions) за период'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('organization_usage_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_usage_pkey')),
    sa.UniqueConstraint('organization_id', 'period_start', name=op.f('uq_organization_usage_org_period'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('organization_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_usage_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_usage_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_usage_org_period'), ['organization_id', 'period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_usage_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###

