"""add deepsek

Revision ID: 3a68f08bcc0d
Revises: e1f2a3b4c5d6
Create Date: 2026-01-02 08:13:58.301278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a68f08bcc0d'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment='Название ключа, заданное пользователем',
               existing_nullable=False)
        batch_op.alter_column('key_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Bcrypt хеш API ключа',
               existing_nullable=False)
        batch_op.alter_column('prefix',
               existing_type=sa.VARCHAR(length=16),
               comment='Префикс ключа для идентификации (sk_xxxxx...)',
               existing_nullable=False)
        batch_op.alter_column('last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Время последнего использования ключа',
               existing_nullable=True)
        batch_op.alter_column('request_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Количество запросов с этим ключом',
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Активен ли ключ (можно отключить без удаления)',
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_api_keys_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.alter_column('is_debug',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.alter_column('is_debug',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_created_at'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Активен ли ключ (можно отключить без удаления)',
               existing_nullable=False)
        batch_op.alter_column('request_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Количество запросов с этим ключом',
               existing_nullable=False)
        batch_op.alter_column('last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Время последнего использования ключа',
               existing_nullable=True)
        batch_op.alter_column('prefix',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='Префикс ключа для идентификации (sk_xxxxx...)',
               existing_nullable=False)
        batch_op.alter_column('key_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bcrypt хеш API ключа',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Название ключа, заданное пользователем',
               existing_nullable=False)

    # ### end Alembic commands ###

