"""add templates

Revision ID: c030bb311591
Revises: 7706c3da6ed1
Create Date: 2026-01-29 13:31:22.665469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c030bb311591'
down_revision = '7706c3da6ed1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_templates',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_templates', schema=None) as batch_op:
        batch_op.create_index('ix_node_templates_config_gin', ['config'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_node_templates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_templates_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_node_templates_project_id_created_at', ['project_id', 'created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Флаг администратора',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Флаг администратора',
               existing_nullable=False)

    with op.batch_alter_table('node_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_node_templates_project_id_created_at')
        batch_op.drop_index(batch_op.f('ix_node_templates_project_id'))
        batch_op.drop_index(batch_op.f('ix_node_templates_created_at'))
        batch_op.drop_index('ix_node_templates_config_gin', postgresql_using='gin')

    op.drop_table('node_templates')
    # ### end Alembic commands ###

