"""add own key cost

Revision ID: ce99c0da1bed
Revises: c749b0c8184c
Create Date: 2026-02-03 20:25:09.853228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce99c0da1bed'
down_revision = 'c749b0c8184c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('own_key_cost_usd', sa.Float(), nullable=True, comment='Стоимость в USD при использовании собственного API ключа'))

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('own_key_cost_usd', sa.Numeric(precision=20, scale=8), nullable=True, comment='Общая стоимость в USD при использовании собственных API ключей'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_column('own_key_cost_usd')

    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.drop_column('own_key_cost_usd')

    # ### end Alembic commands ###

