"""change int to decmial

Revision ID: 5c31ad68cf4d
Revises: 6dc619ebd9ef
Create Date: 2026-01-15 15:37:36.412914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c31ad68cf4d'
down_revision = '6dc619ebd9ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.alter_column('amount_credits',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=8),
               comment='Сумма в кредитах (+ начисление, - списание, до 8 знаков)',
               existing_comment='Сумма в кредитах (+ начисление, - списание)',
               existing_nullable=False)
        batch_op.alter_column('amount_usd',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=15, scale=10),
               comment='Сумма в USD (+ начисление, - списание, до 10 знаков)',
               existing_comment='Сумма в USD (+ начисление, - списание)',
               existing_nullable=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('credits_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=8),
               comment='Текущий баланс кредитов (до 8 знаков после запятой)',
               existing_comment='Текущий баланс кредитов',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.create_index('ix_organizations_slug', ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('ix_organizations_slug')
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)
        batch_op.alter_column('credits_balance',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.INTEGER(),
               comment='Текущий баланс кредитов',
               existing_comment='Текущий баланс кредитов (до 8 знаков после запятой)',
               existing_nullable=False)

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.alter_column('amount_usd',
               existing_type=sa.Numeric(precision=15, scale=10),
               type_=sa.NUMERIC(precision=10, scale=6),
               comment='Сумма в USD (+ начисление, - списание)',
               existing_comment='Сумма в USD (+ начисление, - списание, до 10 знаков)',
               existing_nullable=False)
        batch_op.alter_column('amount_credits',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.INTEGER(),
               comment='Сумма в кредитах (+ начисление, - списание)',
               existing_comment='Сумма в кредитах (+ начисление, - списание, до 8 знаков)',
               existing_nullable=False)

    # ### end Alembic commands ###

