"""fix plantier

Revision ID: b97582ccbc34
Revises: ac62578cd41b
Create Date: 2026-01-13 13:25:05.399905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b97582ccbc34'
down_revision = 'ac62578cd41b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=postgresql.ENUM('FREE', 'STARTER', 'PROFESSIONAL', 'TEAM', 'ENTERPRISE', name='plantier'),
               server_default=None,
               type_=sa.String(length=50),
               existing_comment='Тарифный план организации',
               existing_nullable=False)
        batch_op.alter_column('billing_period_start',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='Дата начала биллингового периода',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.create_index('ix_organizations_slug', ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('ix_organizations_slug')
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)
        batch_op.alter_column('billing_period_start',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='Дата начала биллингового периода',
               existing_nullable=False)
        batch_op.alter_column('plan',
               existing_type=sa.String(length=50),
               server_default=sa.text("'FREE'::plantier"),
               type_=postgresql.ENUM('FREE', 'STARTER', 'PROFESSIONAL', 'TEAM', 'ENTERPRISE', name='plantier'),
               existing_comment='Тарифный план организации',
               existing_nullable=False)

    # ### end Alembic commands ###

