"""add onboarding

Revision ID: b2e26c8495f9
Revises: d862e27715cc
Create Date: 2026-01-11 09:34:48.038862

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b2e26c8495f9"
down_revision = "d862e27715cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "onboarding",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=False,
                server_default="{}",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("onboarding")

    # ### end Alembic commands ###
