"""update migrations

Revision ID: 6f29c14b4ea3
Revises: b2e26c8495f9
Create Date: 2026-01-12 14:59:34.599725

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6f29c14b4ea3"
down_revision = "b2e26c8495f9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_sessions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "client_id",
            sa.String(length=255),
            nullable=False,
            comment="Уникальный идентификатор клиента в рамках проекта",
        ),
        sa.Column(
            "state",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Состояние проектных переменных",
        ),
        sa.Column(
            "meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Метаданные клиента",
        ),
        sa.Column(
            "execution_count",
            sa.Integer(),
            nullable=False,
            comment="Количество выполнений workflows",
        ),
        sa.Column(
            "total_tokens_used",
            sa.Integer(),
            nullable=False,
            comment="Суммарное количество использованных токенов",
        ),
        sa.Column(
            "total_cost",
            sa.Float(),
            nullable=False,
            comment="Суммарная стоимость (USD)",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активна ли сессия"
        ),
        sa.Column(
            "last_activity_at",
            sa.DateTime(),
            nullable=True,
            comment="Время последней активности",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "client_id", name="uq_client_session_project_client"
        ),
    )
    with op.batch_alter_table("client_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_client_sessions_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_client_sessions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_client_sessions_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            "ix_client_sessions_last_activity", ["last_activity_at"], unique=False
        )
        batch_op.create_index(
            "ix_client_sessions_project_active",
            ["project_id", "is_active"],
            unique=False,
        )
        batch_op.create_index(
            "ix_client_sessions_project_client",
            ["project_id", "client_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_client_sessions_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "client_session_id",
                sa.Uuid(),
                nullable=True,
                comment="Client session для project-level state между workflows",
            )
        )
        batch_op.create_index(
            "ix_executions_client_session", ["client_session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_executions_client_session_id"),
            ["client_session_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            None, "client_sessions", ["client_session_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.create_index(
            batch_op.f("ix_organizations_slug"), ["slug"], unique=True
        )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "state_schema",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=False,
                server_default=sa.text("'[]'::jsonb"),
                comment="Схема проектных переменных для ClientSession",
            )
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "onboarding",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "onboarding",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            existing_nullable=False,
        )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("state_schema")

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.create_index(
            batch_op.f("ix_organizations_slug"), ["slug"], unique=False
        )

    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_executions_client_session_id"))
        batch_op.drop_index("ix_executions_client_session")
        batch_op.drop_column("client_session_id")

    with op.batch_alter_table("client_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_sessions_project_id"))
        batch_op.drop_index("ix_client_sessions_project_client")
        batch_op.drop_index("ix_client_sessions_project_active")
        batch_op.drop_index("ix_client_sessions_last_activity")
        batch_op.drop_index(batch_op.f("ix_client_sessions_is_active"))
        batch_op.drop_index(batch_op.f("ix_client_sessions_created_at"))
        batch_op.drop_index(batch_op.f("ix_client_sessions_client_id"))

    op.drop_table("client_sessions")
    # ### end Alembic commands ###
