"""add is_admin

Revision ID: 7706c3da6ed1
Revises: c5b9682588df
Create Date: 2026-01-28 10:11:30.176361

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7706c3da6ed1"
down_revision = "c5b9682588df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.create_index(
            batch_op.f("ix_organizations_slug"), ["slug"], unique=True
        )

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_order_id"))
        batch_op.create_index(
            batch_op.f("ix_payments_order_id"), ["order_id"], unique=True
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_admin",
                sa.Boolean(),
                nullable=False,
                server_default="false",
                comment="Флаг администратора",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_admin")

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_order_id"))
        batch_op.create_index(
            batch_op.f("ix_payments_order_id"), ["order_id"], unique=False
        )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.create_index(
            batch_op.f("ix_organizations_slug"), ["slug"], unique=False
        )

    # ### end Alembic commands ###
