"""nullable to token

Revision ID: 4b347362bc9c
Revises: ab2642f3e9ce
Create Date: 2026-01-10 07:25:39.195288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b347362bc9c'
down_revision = 'ab2642f3e9ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('token_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='API key used to create this chat session (null for debug mode)',
               existing_comment='API key used to create this chat session')

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.alter_column('token_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='API key used to execute this workflow (null for debug mode)',
               existing_comment='API key used to execute this workflow')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.alter_column('token_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='API key used to execute this workflow',
               existing_comment='API key used to execute this workflow (null for debug mode)')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('token_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='API key used to create this chat session',
               existing_comment='API key used to create this chat session (null for debug mode)')

    # ### end Alembic commands ###

