"""add name and output

Revision ID: 75acbd323962
Revises: 3a47f9f1f48a
Create Date: 2026-03-01 20:21:00.078820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75acbd323962'
down_revision = '3a47f9f1f48a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Выходные данные workflow (output от END ноды)'))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=False)

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_column('output')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###

