"""add organizaitons

Revision ID: 0fbb190c9795
Revises: a1b2c3d4e5f6
Create Date: 2026-01-10 05:35:26.260974

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0fbb190c9795"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    from uuid import uuid4
    from datetime import datetime

    # ### commands auto generated by Alembic - please adjust! ###
    # Шаг 1: Создаем новые таблицы
    op.create_table(
        "organizations",
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Название организации",
        ),
        sa.Column(
            "slug",
            sa.String(length=255),
            nullable=False,
            comment="URL-friendly идентификатор",
        ),
        sa.Column(
            "description",
            sa.String(length=1000),
            nullable=True,
            comment="Описание организации",
        ),
        sa.Column(
            "owner_id", sa.Uuid(), nullable=False, comment="Владелец организации"
        ),
        sa.Column(
            "is_personal",
            sa.Boolean(),
            nullable=False,
            comment="Персональная организация (создается при регистрации)",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активна ли организация"
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organizations_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_organizations_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_organizations_is_personal"), ["is_personal"], unique=False
        )
        batch_op.create_index("ix_organizations_owner_id", ["owner_id"], unique=False)
        batch_op.create_index("ix_organizations_slug", ["slug"], unique=False)

    op.create_table(
        "organization_users",
        sa.Column(
            "organization_id", sa.Uuid(), nullable=False, comment="ID организации"
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False, comment="ID пользователя"),
        sa.Column(
            "is_owner",
            sa.Boolean(),
            nullable=False,
            comment="Является ли пользователь владельцем организации",
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(),
            nullable=False,
            comment="Дата вступления в организацию",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_organization_user"),
    )
    with op.batch_alter_table("organization_users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organization_users_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_organization_users_org_user",
            ["organization_id", "user_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_organization_users_organization_id", ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_organization_users_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "projects",
        sa.Column(
            "organization_id", sa.Uuid(), nullable=False, comment="ID организации"
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Название проекта"
        ),
        sa.Column(
            "slug",
            sa.String(length=255),
            nullable=False,
            comment="URL-friendly идентификатор (уникален в рамках организации)",
        ),
        sa.Column(
            "description",
            sa.String(length=1000),
            nullable=True,
            comment="Описание проекта",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активен ли проект"
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "slug", name="uq_project_org_slug"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_projects_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_projects_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            "ix_projects_org_active", ["organization_id", "is_active"], unique=False
        )
        batch_op.create_index(
            "ix_projects_organization_id", ["organization_id"], unique=False
        )
        batch_op.create_index("ix_projects_slug", ["slug"], unique=False)

    # Шаг 2: Мигрируем данные - создаем организации и проекты для существующих пользователей
    connection = op.get_bind()
    users = connection.execute(sa.text("SELECT id, email FROM users")).fetchall()

    user_project_map = {}  # Словарь user_id -> project_id для миграции данных

    for user in users:
        user_id = user[0]
        email = user[1]

        # Создаем персональную организацию
        org_id = uuid4()
        org_slug = f"personal-{str(uuid4())[:8]}"
        now = datetime.utcnow()

        connection.execute(
            sa.text(
                """
                INSERT INTO organizations (id, name, slug, owner_id, is_personal, is_active, created_at, updated_at)
                VALUES (:id, :name, :slug, :owner_id, true, true, :now, :now)
            """
            ),
            {
                "id": org_id,
                "name": f"Personal ({email})",
                "slug": org_slug,
                "owner_id": user_id,
                "now": now,
            },
        )

        # Создаем запись в organization_users
        connection.execute(
            sa.text(
                """
                INSERT INTO organization_users (id, organization_id, user_id, is_owner, joined_at, created_at, updated_at)
                VALUES (:id, :organization_id, :user_id, true, :now, :now, :now)
            """
            ),
            {
                "id": uuid4(),
                "organization_id": org_id,
                "user_id": user_id,
                "now": now,
            },
        )

        # Создаем дефолтный проект
        project_id = uuid4()
        connection.execute(
            sa.text(
                """
                INSERT INTO projects (id, organization_id, name, slug, is_active, created_at, updated_at, description)
                VALUES (:id, :organization_id, 'Default Project', 'default', true, :now, :now, 'Your default project')
            """
            ),
            {
                "id": project_id,
                "organization_id": org_id,
                "now": now,
            },
        )

        # Сохраняем соответствие user_id -> project_id для миграции данных
        user_project_map[str(user_id)] = project_id

    # Шаг 3: Добавляем current_organization_id в users
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("current_organization_id", sa.Uuid(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_users_current_organization_id"),
            ["current_organization_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_users_current_organization_id_organizations",
            "organizations",
            ["current_organization_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # Заполняем current_organization_id для пользователей
    for user in users:
        user_id = user[0]
        # Находим организацию пользователя
        org = connection.execute(
            sa.text(
                "SELECT id FROM organizations WHERE owner_id = :user_id AND is_personal = true LIMIT 1"
            ),
            {"user_id": user_id},
        ).fetchone()
        if org:
            connection.execute(
                sa.text(
                    "UPDATE users SET current_organization_id = :org_id WHERE id = :user_id"
                ),
                {"org_id": org[0], "user_id": user_id},
            )

    # Шаг 4: Добавляем колонки project_id как NULLABLE и заполняем их
    # 4.1 API Keys
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.Uuid(), nullable=True))

    # Мигрируем данные api_keys
    for user_id_str, project_id in user_project_map.items():
        connection.execute(
            sa.text(
                "UPDATE api_keys SET project_id = :project_id WHERE user_id = :user_id"
            ),
            {"project_id": project_id, "user_id": user_id_str},
        )

    # Делаем project_id NOT NULL и добавляем foreign key
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.alter_column("project_id", nullable=False)
        batch_op.drop_index(batch_op.f("ix_api_keys_user_id"))
        batch_op.drop_index("ix_api_keys_user_id_active")
        batch_op.create_index(
            batch_op.f("ix_api_keys_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            "ix_api_keys_project_id_active", ["project_id", "is_active"], unique=False
        )
        batch_op.drop_constraint("fk_api_keys_user_id_users", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_api_keys_project_id_projects",
            "projects",
            ["project_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("user_id")

    # 4.2 Credentials
    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.Uuid(), nullable=True))

    # Мигрируем данные credentials
    for user_id_str, project_id in user_project_map.items():
        connection.execute(
            sa.text(
                "UPDATE credentials SET project_id = :project_id WHERE user_id = :user_id"
            ),
            {"project_id": project_id, "user_id": user_id_str},
        )

    # Делаем project_id NOT NULL и добавляем foreign key
    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.alter_column("project_id", nullable=False)
        batch_op.drop_index(batch_op.f("ix_credentials_user_id"))
        batch_op.create_index(
            batch_op.f("ix_credentials_project_id"), ["project_id"], unique=False
        )
        batch_op.drop_constraint("credentials_user_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_credentials_project_id_projects",
            "projects",
            ["project_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("user_id")

    # 4.3 Workflows
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.Uuid(), nullable=True))
        batch_op.add_column(
            sa.Column("published_for_workflow_id", sa.Uuid(), nullable=True)
        )
        batch_op.add_column(sa.Column("version", sa.Integer(), nullable=True))

    # Мигрируем данные workflows
    for user_id_str, project_id in user_project_map.items():
        connection.execute(
            sa.text(
                "UPDATE workflows SET project_id = :project_id WHERE user_id = :user_id"
            ),
            {"project_id": project_id, "user_id": user_id_str},
        )

    # Делаем project_id NOT NULL и добавляем foreign key
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.alter_column("project_id", nullable=False)
        batch_op.drop_index(batch_op.f("ix_workflows_user_id"))
        batch_op.drop_index("ix_workflows_user_id_created_at")
        batch_op.create_index(
            batch_op.f("ix_workflows_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            "ix_workflows_project_id_created_at",
            ["project_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_workflows_published_for_workflow_id",
            ["published_for_workflow_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_workflows_published_for_workflow_id_version",
            ["published_for_workflow_id", "version"],
            unique=False,
        )
        batch_op.drop_constraint("workflows_user_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_workflows_published_for_workflow_id_workflows",
            "workflows",
            ["published_for_workflow_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_workflows_project_id_projects",
            "projects",
            ["project_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("user_id")

    # Шаг 5: Обновляем chat_sessions
    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.alter_column(
            "is_debug",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Шаг 1: Добавляем обратно user_id колонки как NULLABLE
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True)
        )

    # Шаг 2: Восстанавливаем user_id из project_id через организации
    connection = op.get_bind()

    # Workflows
    connection.execute(
        sa.text(
            """
        UPDATE workflows w
        SET user_id = o.owner_id
        FROM projects p
        JOIN organizations o ON p.organization_id = o.id
        WHERE w.project_id = p.id
    """
        )
    )

    # Credentials
    connection.execute(
        sa.text(
            """
        UPDATE credentials c
        SET user_id = o.owner_id
        FROM projects p
        JOIN organizations o ON p.organization_id = o.id
        WHERE c.project_id = p.id
    """
        )
    )

    # API Keys
    connection.execute(
        sa.text(
            """
        UPDATE api_keys a
        SET user_id = o.owner_id
        FROM projects p
        JOIN organizations o ON p.organization_id = o.id
        WHERE a.project_id = p.id
    """
        )
    )

    # Шаг 3: Делаем user_id NOT NULL и восстанавливаем индексы/foreign keys
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.alter_column("user_id", nullable=False)
        batch_op.drop_constraint(
            "fk_workflows_published_for_workflow_id_workflows", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_workflows_project_id_projects", type_="foreignkey")
        batch_op.create_foreign_key(
            "workflows_user_id_fkey", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_index("ix_workflows_published_for_workflow_id_version")
        batch_op.drop_index("ix_workflows_published_for_workflow_id")
        batch_op.drop_index("ix_workflows_project_id_created_at")
        batch_op.drop_index(batch_op.f("ix_workflows_project_id"))
        batch_op.create_index(
            "ix_workflows_user_id_created_at", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workflows_user_id"), ["user_id"], unique=False
        )
        batch_op.drop_column("version")
        batch_op.drop_column("published_for_workflow_id")
        batch_op.drop_column("project_id")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_users_current_organization_id_organizations", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_users_current_organization_id"))
        batch_op.drop_column("current_organization_id")

    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.alter_column("user_id", nullable=False)
        batch_op.drop_constraint(
            "fk_credentials_project_id_projects", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "credentials_user_id_fkey", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_index(batch_op.f("ix_credentials_project_id"))
        batch_op.create_index(
            batch_op.f("ix_credentials_user_id"), ["user_id"], unique=False
        )
        batch_op.drop_column("project_id")

    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.alter_column(
            "is_debug",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=False,
        )

    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.alter_column("user_id", nullable=False)
        batch_op.drop_constraint("fk_api_keys_project_id_projects", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_api_keys_user_id_users",
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_index("ix_api_keys_project_id_active")
        batch_op.drop_index(batch_op.f("ix_api_keys_project_id"))
        batch_op.create_index(
            "ix_api_keys_user_id_active", ["user_id", "is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_api_keys_user_id"), ["user_id"], unique=False
        )
        batch_op.drop_column("project_id")

    # Шаг 4: Удаляем новые таблицы
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("ix_projects_slug")
        batch_op.drop_index("ix_projects_organization_id")
        batch_op.drop_index("ix_projects_org_active")
        batch_op.drop_index(batch_op.f("ix_projects_is_active"))
        batch_op.drop_index(batch_op.f("ix_projects_created_at"))

    op.drop_table("projects")

    with op.batch_alter_table("organization_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organization_users_user_id"))
        batch_op.drop_index("ix_organization_users_organization_id")
        batch_op.drop_index("ix_organization_users_org_user")
        batch_op.drop_index(batch_op.f("ix_organization_users_created_at"))

    op.drop_table("organization_users")

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index("ix_organizations_slug")
        batch_op.drop_index("ix_organizations_owner_id")
        batch_op.drop_index(batch_op.f("ix_organizations_is_personal"))
        batch_op.drop_index(batch_op.f("ix_organizations_is_active"))
        batch_op.drop_index(batch_op.f("ix_organizations_created_at"))

    op.drop_table("organizations")
    # ### end Alembic commands ###
