"""add is debug

Revision ID: c749b0c8184c
Revises: f03e23f487d0
Create Date: 2026-02-03 15:17:58.738551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c749b0c8184c'
down_revision = 'f03e23f487d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_debug', sa.Boolean(), nullable=False, server_default="false"))
        batch_op.create_index(batch_op.f('ix_client_sessions_is_debug'), ['is_debug'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_sessions_is_debug'))
        batch_op.drop_column('is_debug')

    # ### end Alembic commands ###

