"""add http block

Revision ID: d862e27715cc
Revises: 4b347362bc9c
Create Date: 2026-01-11 09:07:15.639792

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d862e27715cc"
down_revision = "4b347362bc9c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Добавляем новое значение HTTP_REQUEST в enum nodetype
    op.execute("ALTER TYPE nodetype ADD VALUE IF NOT EXISTS 'HTTP_REQUEST'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.create_index("ix_organizations_slug", ["slug"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index("ix_organizations_slug")
        batch_op.create_index(
            batch_op.f("ix_organizations_slug"), ["slug"], unique=True
        )

    # ### end Alembic commands ###
