"""remove user_id from executions

Revision ID: ab2642f3e9ce
Revises: 0fbb190c9795
Create Date: 2026-01-10 06:17:39.803094

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab2642f3e9ce"
down_revision = "0fbb190c9795"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # IMPORTANT: Delete all existing chat sessions and executions
    # because we cannot assign token_id to existing records
    print("⚠️  Deleting all existing chat sessions and executions...")
    op.execute("DELETE FROM chat_sessions")
    op.execute("DELETE FROM executions")
    print("✅ Deleted all chat sessions and executions")

    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "token_id",
                sa.Uuid(),
                nullable=False,
                comment="API key used to create this chat session",
            )
        )
        batch_op.drop_index(batch_op.f("ix_chat_sessions_user_active"))
        batch_op.drop_index(batch_op.f("ix_chat_sessions_user_id"))
        batch_op.create_index(
            "ix_chat_sessions_token_active", ["token_id", "is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chat_sessions_token_id"), ["token_id"], unique=False
        )
        batch_op.drop_constraint(
            batch_op.f("chat_sessions_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "api_keys", ["token_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "token_id",
                sa.Uuid(),
                nullable=False,
                comment="API key used to execute this workflow",
            )
        )
        batch_op.drop_index(batch_op.f("ix_executions_user_id"))
        batch_op.drop_index(batch_op.f("ix_executions_user_status"))
        batch_op.create_index(
            batch_op.f("ix_executions_token_id"), ["token_id"], unique=False
        )
        batch_op.create_index(
            "ix_executions_token_status", ["token_id", "status"], unique=False
        )
        batch_op.drop_constraint(
            batch_op.f("executions_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "api_keys", ["token_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.create_index(
            batch_op.f("ix_organizations_slug"), ["slug"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.create_index(
            batch_op.f("ix_organizations_slug"), ["slug"], unique=False
        )

    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("executions_user_id_fkey"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_index("ix_executions_token_status")
        batch_op.drop_index(batch_op.f("ix_executions_token_id"))
        batch_op.create_index(
            batch_op.f("ix_executions_user_status"), ["user_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_executions_user_id"), ["user_id"], unique=False
        )
        batch_op.drop_column("token_id")

    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("chat_sessions_user_id_fkey"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_index(batch_op.f("ix_chat_sessions_token_id"))
        batch_op.drop_index("ix_chat_sessions_token_active")
        batch_op.create_index(
            batch_op.f("ix_chat_sessions_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chat_sessions_user_active"),
            ["user_id", "is_active"],
            unique=False,
        )
        batch_op.drop_column("token_id")

    # ### end Alembic commands ###
