"""fix_type

Revision ID: c5b9682588df
Revises: d62f737587b9
Create Date: 2026-01-24 21:51:26.549470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b9682588df'
down_revision = 'd62f737587b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.create_index('ix_organizations_slug', ['slug'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('rebill_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='ID для автоматического списания (RebillId от Tinkoff)',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.create_index('ix_payments_order_id', ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_order_id')
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=True)
        batch_op.alter_column('rebill_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='ID для автоматического списания (RebillId от Tinkoff)',
               existing_nullable=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('ix_organizations_slug')
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###

