"""add utm 


Revision ID: 157ffebb88d5
Revises: a7776fcd12e8
Create Date: 2026-02-19 12:52:37.986744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157ffebb88d5'
down_revision = 'a7776fcd12e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.create_index('ix_payments_order_id', ['order_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utm_source', sa.String(length=255), nullable=True, comment='Источник трафика'))
        batch_op.add_column(sa.Column('utm_medium', sa.String(length=255), nullable=True, comment='Канал маркетинга'))
        batch_op.add_column(sa.Column('utm_campaign', sa.String(length=255), nullable=True, comment='Название кампании'))
        batch_op.add_column(sa.Column('utm_content', sa.String(length=255), nullable=True, comment='Идентификатор контента'))
        batch_op.add_column(sa.Column('utm_term', sa.String(length=255), nullable=True, comment='Ключевое слово поиска'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('utm_term')
        batch_op.drop_column('utm_content')
        batch_op.drop_column('utm_campaign')
        batch_op.drop_column('utm_medium')
        batch_op.drop_column('utm_source')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_order_id')
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=True)

    # ### end Alembic commands ###

