"""add documents

Revision ID: 3a47f9f1f48a
Revises: 157ffebb88d5
Create Date: 2026-02-21 14:02:33.061080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a47f9f1f48a'
down_revision = '157ffebb88d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('total_characters', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_bases_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_knowledge_bases_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_knowledge_bases_project_id_created_at', ['project_id', 'created_at'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_knowledge_documents_kb_id', ['knowledge_base_id'], unique=False)
        batch_op.create_index('ix_knowledge_documents_kb_id_created_at', ['knowledge_base_id', 'created_at'], unique=False)
        batch_op.create_index('ix_knowledge_documents_kb_id_hash', ['knowledge_base_id', 'content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_knowledge_base_id'), ['knowledge_base_id'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.create_index('ix_organizations_slug', ['slug'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('ix_organizations_slug')
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_knowledge_base_id'))
        batch_op.drop_index('ix_knowledge_documents_kb_id_hash')
        batch_op.drop_index('ix_knowledge_documents_kb_id_created_at')
        batch_op.drop_index('ix_knowledge_documents_kb_id')
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_content_hash'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_bases_project_id_created_at')
        batch_op.drop_index('ix_knowledge_bases_project_id')
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_created_at'))

    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###

