"""add_chat_plan_to_organizations_and_source_to_workflows

Revision ID: 6243d9f0ba55
Revises: 75acbd323962
Create Date: 2026-03-20 10:50:18.618804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6243d9f0ba55'
down_revision = '75acbd323962'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_plan', sa.String(length=50), server_default='free', nullable=False, comment='Тарифный план Chat-виджетов'))
        batch_op.create_index(batch_op.f('ix_organizations_chat_plan'), ['chat_plan'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.create_index('ix_payments_order_id', ['order_id'], unique=False)

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), server_default='assemblix', nullable=False, comment='Продукт-источник: assemblix или chat'))
        batch_op.create_index(batch_op.f('ix_workflows_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_source'))
        batch_op.drop_column('source')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_order_id')
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_chat_plan'))
        batch_op.drop_column('chat_plan')

    # ### end Alembic commands ###

