"""add voice_agents

Revision ID: ea30b38221b9
Revises: f7a8b9c0d1e2
Create Date: 2026-08-06 09:12:22.187144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea30b38221b9'
down_revision = 'f7a8b9c0d1e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_agents',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_agents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_agents_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_agents_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_voice_agents_project_id_created_at', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_agents', schema=None) as batch_op:
        batch_op.drop_index('ix_voice_agents_project_id_created_at')
        batch_op.drop_index(batch_op.f('ix_voice_agents_project_id'))
        batch_op.drop_index(batch_op.f('ix_voice_agents_is_active'))
        batch_op.drop_index(batch_op.f('ix_voice_agents_created_at'))

    op.drop_table('voice_agents')
    # ### end Alembic commands ###
