"""add credits to billing

Revision ID: 01c0a8478c02
Revises: b97582ccbc34
Create Date: 2026-01-15 08:46:18.522090

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "01c0a8478c02"
down_revision = "b97582ccbc34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_transactions",
        sa.Column(
            "organization_id", sa.Uuid(), nullable=False, comment="ID организации"
        ),
        sa.Column(
            "amount_credits",
            sa.Integer(),
            nullable=False,
            comment="Сумма в кредитах (+ начисление, - списание)",
        ),
        sa.Column(
            "amount_usd",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
            comment="Сумма в USD (+ начисление, - списание)",
        ),
        sa.Column(
            "type", sa.String(length=50), nullable=False, comment="Тип транзакции"
        ),
        sa.Column(
            "execution_id",
            sa.Uuid(),
            nullable=True,
            comment="ID выполнения (для LLM_USAGE, REQUEST_FEE)",
        ),
        sa.Column(
            "description", sa.Text(), nullable=False, comment="Описание транзакции"
        ),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Метаданные транзакции (модель, токены, провайдер и т.д.)",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("credit_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_credit_transactions_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_credit_transactions_execution_id", ["execution_id"], unique=False
        )
        batch_op.create_index(
            "ix_credit_transactions_org_created",
            ["organization_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_credit_transactions_organization_id", ["organization_id"], unique=False
        )
        batch_op.create_index("ix_credit_transactions_type", ["type"], unique=False)

    # Добавляем колонки как nullable сначала
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "credits_balance",
                sa.Integer(),
                nullable=True,
                comment="Текущий баланс кредитов",
            )
        )
        batch_op.add_column(
            sa.Column(
                "credits_period_start",
                sa.Date(),
                nullable=True,
                comment="Дата начала текущего кредитного периода",
            )
        )
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.create_index(
            batch_op.f("ix_organizations_slug"), ["slug"], unique=True
        )

    # Заполняем существующие организации значениями по умолчанию (1000 кредитов)
    op.execute(
        """
        UPDATE organizations 
        SET 
            credits_balance = 1000,
            credits_period_start = CURRENT_DATE
        WHERE credits_balance IS NULL
    """
    )

    # Делаем колонки NOT NULL
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.alter_column("credits_balance", nullable=False)
        batch_op.alter_column("credits_period_start", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.create_index(
            batch_op.f("ix_organizations_slug"), ["slug"], unique=False
        )
        batch_op.drop_column("credits_period_start")
        batch_op.drop_column("credits_balance")

    with op.batch_alter_table("credit_transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_credit_transactions_type")
        batch_op.drop_index("ix_credit_transactions_organization_id")
        batch_op.drop_index("ix_credit_transactions_org_created")
        batch_op.drop_index("ix_credit_transactions_execution_id")
        batch_op.drop_index(batch_op.f("ix_credit_transactions_created_at"))

    op.drop_table("credit_transactions")
    # ### end Alembic commands ###
